name: "Landscapes CI"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test_suite:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install required apt packages
        run: |
          sudo apt-get -y install libpq-dev
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@08245253a76fa4d1e459b7809579c62bd9eb718a # v1.111
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:setup
      - name: Rails tests
        run: bin/rails test
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Node dependencies
        run: |
          yarn --frozen-lockfile
      - name: Webpack
        run: bin/webpack
      - name: Install Playwright
        # Install Webkit dependencies. Seems to need installing in a couple of steps.
        run: |
          sudo apt-get -y install libegl1 libgles2 libopengl0 libwoff1 libharfbuzz-icu0 libopenjp2-7 libenchant1c2a
          sudo apt-get -y install libwebpdemux2 libenchant-2-2 libhyphen0 libevdev2 libx264-155 libopus0
          sudo apt-get -y install libgstreamer1.0-0 libgstreamer-gl1.0-0 libgst7
          yarn add playwright
      - name: Run End to End tests
        run: |
          yarn playwright test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report